global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    project: 'etl-congresso'

scrape_configs:
  - job_name: "etl-congresso"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["etl-app:8080"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "etl-congresso-app"
